rtp:
  cooldown-seconds: 30
  default-menu: "overworld" # /rtp yazılınca ilk burası açılır
  menus:
    overworld:
      title: ":offset_-8::rtp_menu_overworld:"
      rows: 6
      items:
        bg_waterfall:
          slot: 47
          material: "itemsadder-teleportation_hub:waterfall_animation"
        nether_tab:
          slot: 23
          material: "itemsadder-teleportation_hub:nether_icon"
          action: "menu"           # Tıklayınca menüyü değiştirir
          action-value: "nether"   # Hedef menü id'si (Aşağıdaki nether bloğu)
        end_tab:
          slot: 26
          material: "itemsadder-teleportation_hub:end_icon"
          action: "menu"
          action-value: "end"
        location_1:
          slot: 28
          material: "itemsadder-teleportation_hub:rtp_pin"
          name: "&fIşınlanma"
          lore:
            - ""
            - "&#A5ACB8ᴀʟᴀɴ: 5000 x 5000"
            - "&#A5ACB8ʏᴇɴɪʟᴇɴᴍᴇ ѕüʀᴇѕɪ: 7 ᴅᴀᴋɪᴋᴀ"
            - ""
            - " &#58A527→ ışıɴʟᴀɴᴍᴀᴋ ɪçɪɴ ᴛıᴋʟᴀ!"
          action: "rtp"            # Tıklayınca RtpQueueManager'ı tetikler
          action-value: "survival" # BetterRTP'nin atacağı dünya adı

    nether:
      title: ":offset_-8::rtp_menu_nether:"
      rows: 6
      items:
        bg_lava:
          slot: 53
          material: "itemsadder-teleportation_hub:lava_animation"
        overworld_tab:
          slot: 19
          material: "itemsadder-teleportation_hub:overworld_icon"
          action: "menu"
          action-value: "overworld"
        location_1:
          slot: 28
          material: "itemsadder-teleportation_hub:rtp_pin"
          name: "&fIşınlanma"
          lore:
            - ""
            - "&#A5ACB8ᴀʟᴀɴ: 1000 x 1000"
            - " &#58A527→ ışıɴʟᴀɴᴍᴀᴋ ɪçɪɴ ᴛıᴋʟᴀ!"
          action: "rtp"
          action-value: "world_nether"

    end:
      title: ":offset_-8::rtp_menu_end:"
      rows: 6
      items:
        bg_stars:
          slot: 37
          material: "itemsadder-teleportation_hub:star_animation_3"
        overworld_tab:
          slot: 19
          material: "itemsadder-teleportation_hub:overworld_icon"
          action: "menu"
          action-value: "overworld"
        location_1:
          slot: 28
          material: "itemsadder-teleportation_hub:rtp_pin"
          name: "&fIşınlanma"
          lore:
            - ""
            - "&#A5ACB8ᴀʟᴀɴ: 5000 x 5000"
            - " &#58A527→ ışıɴʟᴀɴᴍᴀᴋ ɪçɪɴ ᴛıᴋʟᴀ!"
          action: "rtp"
          action-value: "world_the_end"
# ==========================================
#       MultiLobby - Ana Yapılandırma
# ==========================================

first-join:
  spawn: true # Sunucuya ilk kez girenler spawnda mı doğsun?

spawn:
  warmup-seconds: 3 # Işınlanma bekleme süresi
  cancel-on-move: true # Hareket edince ışınlanma iptal olsun mu?
  # /setspawn veya /setlobby yazıldığında buralar otomatik dolar:
  world: "spawn"
  x: 0.0
  y: 64.0
  z: 0.0
  yaw: 0.0
  pitch: 0.0

void-protect:
  world: "spawn"
  y-threshold: -60.0 # Bu kordinatın altına düşenler ölmeden spawna atılır

# ==========================================
#       Tıklanabilir Sosyal Medya Linkleri
# ==========================================
links:
  discord:
    text: "§9[!] §bDiscord sunucumuza katılmak için §nburaya tıklayın§b!"
    url: "https://discord.gg/risement"
    hover: "§7Tıklayarak sunucumuza katılabilirsiniz."
  tiktok:
    text: "§d[!] §dTikTok hesabımızı takip etmek için §nburaya tıklayın§d!"
    url: "https://tiktok.com/@wolfplayer6001"
    hover: "§7Tıklayarak hesabımıza gidebilirsiniz."
  website:
    text: "§a[!] §aWeb sitemize gitmek için §nburaya tıklayın§a!"
    url: "https://www.risement.net"
    hover: "§7VIP almak veya destek için tıklayın."
  map:
    text: "§e[!] §eCanlı haritamızı açmak için §nburaya tıklayın§e!"
    url: "https://map.risement.net"
    hover: "§7Tarayıcı üzerinden haritayı açmak için tıkla. (SMP olduğu için eklenmedi :D)"

# ==========================================
#       Warp Menü Ayarları
# ==========================================
warp-menu:
  title: "§aWarplar"
  rows: 3

warps:
  orman:
    world: "world"
    x: 100.0
    y: 64.0
    z: 100.0
    yaw: 0.0
    pitch: 0.0
    icon:
      material: OAK_SAPLING
      name: "§eOrman"
      lore:
        - "§7Ormana gidip kasılmaya başla!"
messages:
  bed-taken: "§cYatağın başka bir oyuncu tarafından ele geçirildi!"
  spam-warning: "§cBu kadar hızlı işlem yapamazsın!"
  rtp-queue-joined: "§aRTP kuyruğuna girdin. Önündeki kişi sayısı: §e%pos%"